UuidGenerator URI Resolution Fix
vitruv-tools/Vitruv pull request #424
Opened 2021-02-18 08:22 UTC by HeikoKlare

Corrects the fragment-based URI calculation in the `UuidGeneratorAndResolverImpl` to support the case that the root container is not the root element of the resource of an object (see #423).

Fixes #423.

2021-02-18 09:55 UTC, HeikoKlare commented
✔️ Works with applications (tests)

2021-02-18 10:15 UTC, jGleitz requested changes
I think we should start to be a lot more consequential with unit testing in Vitruv. So I’d suggest that we add a unit test for this particular bug.

2021-02-18 10:15 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +		val fragmentPath = EcoreUtil.getRelativeURIFragmentPath(resourceRoot, object)
What happens if a resource has multiple root elements? In this case we’d need to find the one that contains the `object`, wouldn’t we?

2021-02-18 10:38 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +		val fragmentPath = EcoreUtil.getRelativeURIFragmentPath(resourceRoot, object)
I thought about that as well. In general, Ecore is tied to using only a single root element and when having multiple root elements the first one is kind of "the central one".
Apart from transient states (like code generation for Xtext resources), the only situation I know in which multiple root elements are used are UML stereotypes. But, of course, we need to ensure that assigning UUIDs to stereotypes (or potentially other elements contained in further root elements) works properly. This will require some kind of search. I'll propose an according improvement.

2021-02-18 10:41 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +		val fragmentPath = EcoreUtil.getRelativeURIFragmentPath(resourceRoot, object)
It might make sense to first write a unit test for this situation, to be sure that it would really lead to a bug.

2021-02-18 10:43 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +		val fragmentPath = EcoreUtil.getRelativeURIFragmentPath(resourceRoot, object)
`getRelativeURIFragmentPath` contains this part:

```
if (internalEObject != ancestorEObject && ancestorEObject != null)
    {
      throw new IllegalArgumentException("The ancestor '" + ancestorEObject + "' is not an ancestor of '" + descendantEObject + "'");
    }
```

So we might also just not fix this situation, because we know we would see an exception should the situation ever arise (which is much better than having a silent failure).

2021-02-18 10:47 UTC, HeikoKlare commented
>I think we should start to be a lot more consequential with unit testing in Vitruv. So I’d suggest that we add a unit test for this particular bug.

Yes, I am still working on some tests to provide.

2021-02-18 16:43 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +		val fragmentPath = EcoreUtil.getRelativeURIFragmentPath(resourceRoot, object)
I've added an according fix together with unit tests that led to a bug before.
In fact, the used fragment-based URIs were only a shortcut for resources with a single root elements (this is why the fragment is separated by `//`, as the number of the root element is contained in between (which is optional if there is only one).

2021-02-18 16:44 UTC, HeikoKlare commented
I've added some first test cases specifically for the mentioned bug as well as for the support of multiple root elements. 
They should be sufficient as regression tests for the problems I faced before.

2021-02-18 17:33 UTC, jGleitz requested changes
I have some remarks. Most of them are questions.

2021-02-18 17:33 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			checkState(container !== null, '''some container of «object» must be a root element of its resource''')
```suggestion
			checkState(container !== null, "some container of %s must be a root element of its resource", object)
```

Avoids creating a `StringConcatenationClient` and building the result `String` on every invocation. Builds the string only if the condition fails.

2021-02-18 17:33 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +		val rootElementIndex = resource.contents.indexOf(resourceRoot)
We could remember this index from above (in the first case, it’s `0`, in the second case, we can replace the `contains` with `indexOf`)

2021-02-18 17:33 UTC, jGleitz commented on tests/framework/tools.vitruv.framework.uuid.tests/src/tools/vitruv/framework/uuid/tests/UuidGeneratorAndResolverImplTest.xtend
> +		uuidGeneratorAndResolver = new UuidGeneratorAndResolverImpl(resourceSet, true)
I think the code is easier to read if the field initialization is in the same line as the field declaration (plus, you can omit types then).

But that is not something I’d insist on.

2021-02-18 17:33 UTC, jGleitz commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
Can you explain why we need an additional test model here?

2021-02-18 17:33 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
>  		// has the same topology in the resolving resource set. This assumption holds when we use this method.
I think this comment should go to the top of the method, because it explains what we are planning to do.

2021-02-18 17:33 UTC, jGleitz commented on tests/framework/tools.vitruv.framework.uuid.tests/src/tools/vitruv/framework/uuid/tests/UuidGeneratorAndResolverImplTest.xtend
> +		val parentResolverNonRoot = resourceSet.getEObject(EcoreUtil.getURI(nonRoot), true)
Could read a little nicer if we added a `static extension` import for `EcoreUtil.getURI` and wrote `nonRoot.URI`. Once again, that’s a nit-pick, I am not going to insist on it.

2021-02-18 17:33 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			}
`EcoreUtil` always does a check for cycles in the containment hierarchy when traversing the tree. Should we do this as well?

If we do, we might consider whether we should call `getRelativeURIFragmentPath` at all. It basically does the same traversal of the tree upwards (but with a check for cycles). So we could also just build the URI fragment ourselves with `StringBuilder.insert` while traversing upwards.

2021-02-18 17:41 UTC, HeikoKlare commented on tests/framework/tools.vitruv.framework.uuid.tests/src/tools/vitruv/framework/uuid/tests/UuidGeneratorAndResolverImplTest.xtend
> +		val parentResolverNonRoot = resourceSet.getEObject(EcoreUtil.getURI(nonRoot), true)
That's a great proposal! I'll improve that.

2021-02-18 17:42 UTC, HeikoKlare commented on tests/framework/tools.vitruv.framework.uuid.tests/src/tools/vitruv/framework/uuid/tests/UuidGeneratorAndResolverImplTest.xtend
> +		uuidGeneratorAndResolver = new UuidGeneratorAndResolverImpl(resourceSet, true)
I have to admit that I was not sure whether the order of field initalization is defined and deterministic or whether `resourceSet` argument can be `null`. I forgot to check that but will have a look at it.

2021-02-18 17:45 UTC, HeikoKlare commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
Actually, we do not need an additional model, but a different type of generated code. As the name indicates, the model has `containmentProxies` enabled, which is the think that enables Java elements to be contained in a `Resource` and in another container at the same time (which is not possible otherwise).
We could reuse the `allElementTypes` metamodel and just define an additional genmodel, but I found it bad to have the same classes multiple times just placed in the different packages (i.e., having `Root`, `NotRoot` etc. duplicated).

2021-02-18 17:51 UTC, jGleitz commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
Does enabeling `containmentProxies` break anything else? I’d expect that as long as you do not build weird containment hierarchies, code generated with the option behaves just like code generated without the option.

If so, we could avoid having an additional test metamodel.

2021-02-18 17:52 UTC, jGleitz commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
Note to self: We need to change `ChangeRecorder`, because containment proxies break one of its assumptions: https://github.com/vitruv-tools/Vitruv/blob/master/bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/recording/ChangeRecorder.xtend#L268-L269

2021-02-18 18:02 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +				rootElementIndex = resource.contents.indexOf(container)
`container` might be `null` here!

2021-02-18 18:04 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +				rootElementIndex = resource.contents.indexOf(container)
The whole loop might most easily be written like this. However, it contains a nasty side-effect:

```Xtend
var container = object
while (container !== null && (rootElementIndex = resource.contents.indexOf(container)) != -1) {
    container = container.eContainer
}

2021-02-18 18:05 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			}
That's an interesting point. I assumed that there cannot be cycles in the containment hierarchy. Actually, the `eResource` implementation simply traverses the containments without a check for cycles. So as far as I understand we will already run into a problem when trying to get the resource, do I think we can ignore that case?

Independent from the previous point, I would not replace the usage of `getRelativeURIFragmentPath` with an own implementation using a `StringBuilder` to stay compatible with potential changes in the implementation and avoid duplication of that logic.

2021-02-18 18:16 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			}
> I assumed that there cannot be cycles in the containment hierarchy

Me too. Then I saw that `EcoreUtil` was check for it.

That’s untrue. From `BasicEObjectImpl#eInternalResource`:

```Java
// Since the cycle is detected by checking if we hit "this" again, after many iterations we'll call this method recursively 
// in case we started with something that wasn't part of a cycle but later traversed up to a cycle.
//
if (++count > 100000)
  {
    return eContainer.eInternalResource();
   }
    result = eContainer.eDirectResource();
    if (result != null || eContainer == this)
    {
      break;
    }
```

2021-02-18 18:20 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			}
To be clear: I am not saying that we should check for cycles, I just want to bring up that EMF seems to be prepared for that kind of problem.

2021-02-18 19:31 UTC, HeikoKlare commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
>I’d expect that as long as you do not build weird containment hierarchies, code generated with the option behaves just like code generated without the option.

>If so, we could avoid having an additional test metamodel.

I though about that as well, because I also didn't want to introduce a further, almost redundant metamodel. However, my intent was the following: Every metamodel that we use (except for the JaMoPP metamodel) has `containmentProxies` disabled and this is also the default setting when creating a genmodel. Thus, even if it only makes (or should make) a difference under rather unusual circumstances, I wanted to keep the metamodel used through all of our basic tests conforming to the standard configuration and thus introduced an additional one for this specific case.

However, I am open to discuss this, because having fewer almost redundant metamodels would be great. I just wanted to clarify the reasons for my decision.

2021-02-18 19:43 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			}
Ah, that's right. That kind of cycle check is "interesting". Maybe it's too late for me, but then `eResource` should return `null` in case there is a cycle, shouldn't it? So our implementation will still fail, as it implicitly assumes `eResource` not to return `null`. But in fact, this cannot happen as the caller checks that the object has a resource. So I guess, we cannot run into the situation that there is such a cycle?

2021-02-18 19:59 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +				rootElementIndex = resource.contents.indexOf(container)
Yes, that's probably most elegant, even with the side effect.
Depending on the average structure/size of models it could even be beneficial to copy the resource contents into a `HashSet` and make the containment traversal by checking containment in that set. Then we could, like in the initial solution, calculate the index afterwards. But I am not sure whether the performance and memory overhead for setting up the set outweighs the performance improvement during the search.

2021-02-18 20:03 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +				rootElementIndex = resource.contents.indexOf(container)
At least, the loop header has to check for `==` instead of `!=` ;-)

2021-02-18 21:20 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +				rootElementIndex = resource.contents.indexOf(container)
> But I am not sure whether the performance and memory overhead for setting up the set outweighs the performance improvement during the search.

I doubt it.

2021-02-18 21:24 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +				rootElementIndex = resource.contents.indexOf(container)
Me too. I've already implemented your proposal, but tests are still running.

2021-02-18 21:46 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
>  		// has the same topology in the resolving resource set. This assumption holds when we use this method.
Fixed

2021-02-18 21:57 UTC, jGleitz commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
I think wanting to have the example models to match the ‘typical’ case is sensible. However, I think in this instance it’s quite unlikely that there can be a bug that we would not catch with `containmentProxies` enabled, but would catch with `containmentProxies` disabled. And even if there was, we could test in with all element types 2 once we found it.

Because of this, I think having the one less example metamodel trumps the concern for realistic examples in this instance.

2021-02-18 22:02 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.uuid/src/tools/vitruv/framework/uuid/UuidGeneratorAndResolverImpl.xtend
> +			}
It seems you’re right. Great, that means we’re good!

2021-02-19 07:59 UTC, HeikoKlare commented on bundles/testutils/tools.vitruv.testutils.metamodels/metamodels/allElementTypesWithContainmentProxies.ecore
> +</ecore:EPackage>
That's right. My concern was that `containmentProxies` are a slight derivation of the typical behavior, which many developers will potentially not be aware of that it exists. If it actually leads to some bug, it may be cumbersome to find it (like it was for me to figure out why Java models behave differently, as I was not aware of it either).
But you are probably right that it's pretty unlikely that it will lead to problems at all, especially because the AllElementTypes metamodel will unlikely be used with proxy containments.
So I've removed that additional metamodel.

2021-02-19 08:36 UTC, jGleitz approved these changes
Looks good to me!

2021-02-19 09:21 UTC, HeikoKlare commented
Perfect, thanks for all the great feedback!
I've successfully validated the changes with the applications tests again, so I'll merge this PR.

2021-02-19 10:34 UTC, merged