State-Based Propagation Improvement
vitruv-tools/Vitruv pull request #453
Opened 2021-03-16 16:36 UTC by HeikoKlare

This PR fixes and improves the state-based change propagation. It prepares for state-based propagation of changes in Java by the Java code monitor.
* Fixes essential bugs in the default state-based propagation strategy preventing Java state comparison
* Adds support for creating and deleting resources rather than only for their modification and extends the API accordingly
* Properly extracts the information passed to the `VirtualModel` to perform state-based change propagation
* Properly handles the case that a complete resource is changed and then requires remapping of a `DomainAwareResource` to an ordinary `Resource`
* Adds a bunch of basic test cases for the state-based change propagation

2021-03-16 18:22 UTC, JanWittler requested changes

2021-03-16 18:22 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.domains/src/tools/vitruv/framework/domains/DefaultStateBasedChangeResolutionStrategy.xtend
> +			it.left = it.left.contents.get(0).eResource()
If there is no better alternative like customising the EMF merger to be aware of `DomainAwareResource`, I think we should expose some getter to the underlying resource of a `DomainAwareResource` instead of requiring this workaround. The code makes assumptions which may change in the future and is not understandable at all if not already worked with `DomainAwareResource` before.

2021-03-16 18:40 UTC, JanWittler commented on tests/framework/tools.vitruv.framework.domains.tests/src/tools/vitruv/framework/tests/domains/BasicStateChangePropagationTest.xtend
> +		]
I am wondering whether changing an element's ID is a reasonable scenario for which we should have a test. From my understanding, the ID is static and will not change during an element's lifetime. This assumption is also used by the default state based change resolution strategy as it uses EMF Compare's ID based matching (if an ID is present). Therefore, if there was some domain were the ID is likely to change, it should be configured with a custom resolution strategy where the ID based matching is disabled (and use a separate test case in that case).

2021-03-17 12:05 UTC, jGleitz commented on bundles/framework/tools.vitruv.framework.domains/src/tools/vitruv/framework/domains/DefaultStateBasedChangeResolutionStrategy.xtend
> +			it.left = it.left.contents.get(0).eResource()
I agree, the code effectively exploits a bug in the implementation of `DomainAwareResource`.

2021-03-17 20:12 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.domains/src/tools/vitruv/framework/domains/DefaultStateBasedChangeResolutionStrategy.xtend
> +			it.left = it.left.contents.get(0).eResource()
I agree that this code has to be replaced. However, conditional functionality based on the type of resource does not sound like a proper improvement. I'll try to figure out how to properly adapt that code.

2021-03-17 20:13 UTC, HeikoKlare commented on tests/framework/tools.vitruv.framework.domains.tests/src/tools/vitruv/framework/tests/domains/BasicStateChangePropagationTest.xtend
> +		]
That's true. The test is actually not supposed to test the ID change but to test a replacement of the complete model contents (which, for EMF Compare, is effectively the same). It then tests the proper behavior covered by the code discussed in the other comment.
I'll update the test case accordingly.

2021-03-19 07:58 UTC, HeikoKlare commented on tests/framework/tools.vitruv.framework.domains.tests/src/tools/vitruv/framework/tests/domains/BasicStateChangePropagationTest.xtend
> +		]
I've provided a changed of that test case explicitly focussing on replacing the root element rather than changing its ID.

2021-03-19 10:02 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.domains/src/tools/vitruv/framework/domains/DefaultStateBasedChangeResolutionStrategy.xtend
> +			it.left = it.left.contents.get(0).eResource()
It was even more simple to fix that: We only need a domain-aware resource set for the case that we create a new model, in which we do not apply EMF Compare anyway, because in the other cases the resource contents are only copied into the resource set, which is why domain-related load/save options are irrelevant. So I simplified the resource sets for the other cases (including the one in which EMF Compare is applied) to ordinary resource sets, which makes the workaround obsolete.

2021-03-19 10:05 UTC, JanWittler requested changes

2021-03-19 10:05 UTC, JanWittler commented on tests/framework/tools.vitruv.framework.domains.tests/src/tools/vitruv/framework/tests/domains/BasicStateChangePropagationTest.xtend
> +		]
I would also change this test to not update an element's id.

2021-03-19 10:44 UTC, HeikoKlare commented on tests/framework/tools.vitruv.framework.domains.tests/src/tools/vitruv/framework/tests/domains/BasicStateChangePropagationTest.xtend
> +		]
Thanks for having an eye on that! I thought I checked for other ID replacements in the tests, but obviously I was not successful ;-) 
I've adapted the test case.

2021-03-22 07:15 UTC, merged