Extension of the Families-Person tests and reactions
vitruv-tools/Vitruv pull request #477
Opened 2021-10-28 17:03 UTC by NeumannDirk

In this work package the domain application of Vitruvius using the Families Model and the Persons Model has been (re)implemented in a test driven manner.  This includes the definition of reactions and routines in both directions and the definition of test cases in both directions. To ease this and future implementations, the testutils of the framework have been extended by 3 new [matchers](https://github.com/NeumannDirk/Vitruv/blob/master/bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/matchers/ModelMatchers.xtend#L42-L67).

Since the complexer FamiliesModel already introduces constraints and multiple different attributes, the [reactions of the FamiliesPersonsTest](https://github.com/NeumannDirk/Vitruv/blob/master/bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions) include more reactions and less complex routines. This also leads to more [testcases](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend).

In the PersonsToFamilies direction, these effects are the opposite. There are less [testcases](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend), handeled by less [reactions](https://github.com/NeumannDirk/Vitruv/blob/master/bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions) that call more complex routines. For more details check the current availiable [wiki site](https://github.com/NeumannDirk/Vitruv/wiki/Code-Review).

2021-11-18 09:58 UTC, HeikoKlare requested changes
There are several code-style and semantic issues to fix regarding both the transformations and the tests.

#### Transformations:
See detailed comments for most of the information. In particular, there is much code duplication and the `Persons2Families` transformations contain a variety of unnecessary decisions, leading to (imo) unnecessary transformations and test cases.
The transformations do currently not properly support changes in the model structures (beyond create/delete). In particular, moving a son or daugther from one family to another or making a son/daughter a father/mother of another family will probably not work. This has to be covered by regression tests and potential adaptations of the transformations.

#### Tests:
The test perform some checks validing the source model after changes. In most cases, however, the source model will not be changed, so if performing a validation at all, the comparison model not needs to be created anew but already exists, because it is the one that was created during test execution. On the other hand, the target model is compared by checking for specific elements rather than creating a comparison model to validate against (like it is done for the source model) which would be much more comprehensive and easy to read. 

In addition, particularly the `Persons2Families` tests need to set many results of user interactions. These are, however, set by passing some magic numbers representing the indices of the selection list (using, e.g. `addNextSingleSelection`). This is hard to read and can easily break. Please use methods like `onNextSingleSelection` instead to properly match the required interaction.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
The male will usually have a `lastname` which should match the name of a family to insert him into, shouldn't it? So families should first be filtered according to that and only if some according families remain a selection is necessary. In addition, if the user has selected that the male should be a family, only families not having a father already should be listed imo.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine evaluateFamilyDecisionForNewFather(persons::Male newFather, families::Family chosenFamily) {
This routine does not only `evaluate` something but actually performs changes.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			} else {
You could directly call this in the calling routine, so you do not need to have `chosenFamily=null` as an implicit indicator for creating a new family.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +				if (chosenFamily.lastName.equals(newFather.fullName.split(" ").get(1))) {
What happens if the new male's name only is a single word? This will throw an exception then. Please add a regression test case and update the implementation accordingly.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +					}
In my opinion, this behavior is not required. Why should you create a person and use it to replace a person in an existing family? If there are changes in family relationships, these changes should actually be performed in the families model, not via the persons models.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +				if (chosenFamily.lastName.equals(newFather.fullName.split(" ").get(1))) {
In addition: As mentioned above, families with non-matching last names should not be an option for selection at all.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			newFamily.lastName = newFatherPerson.fullName.split(" ").get(1)
Implicit assumption: see above

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine tryCreateFatherInMatchingFamily_WithFather(persons::Male newFather, families::Family family) {
Should be obsolete (see above).

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			newFatherMember.firstName = newFatherPerson.fullName.split(" ").get(0)
Logic for splitting a persons's name is duplicated all over the file. Please seperate that logic into helper methods with proper exception handling (in particular for persons whose name is only a single word or even empty).

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine replaceFatherInExistingMatchingFamily(persons::Male newFatherPerson, families::Family family) {
Should be obsolete (see above).

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			newFatherMember.familyFather = family
Could be replaced by a single statement, as reference should be bidirectional and setting a new value implicitly removes the old one.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			.choices(differentLastnameOptions).windowModality(WindowModality.MODAL).startInteraction()
I don't get what this has to do with different lastnames. A precondition for this routine is that the lastnames of the family and the person-to-add are equal.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine tryCreateFatherInDifferentlyNamedFamily_WithoutFather(persons::Male newFather, families::Family family) {
Should be obsolete (see above).

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine tryCreateFatherInDifferentlyNamedFamily_WithFather(persons::Male newFather, families::Family family) {
Should be obsolete (see above).

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine evaluateFamilyDecisionForNewSon(persons::Male newSon, families::Family chosenFamily) {
See above: does not only `evaluate` but actually do something.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			newFamily.lastName = newPerson.fullName.split(" ").get(1)
see above: `get(1)` will fail

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		val newFamily = create families::Family and initialize {
Creating a family is the same for fathers, sons, mothers and daughters, to factor out to common routine to avoid duplicate code.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		}
See above: duplicated code

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine createSonInDifferentlyNamedFamily(persons::Male newSon, families::Family family) {
Should be obsolete (see above)

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
Factor this out to helper method to avoid code duplication with male creation

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +}
Same comments as for male creation apply to female creation

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			val String newLastname = person.fullName.split(" ").get(1)
See above: `get(1)` will fail.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
Well, I would not expect that if a new person is created any family with a non-matching name is renamed, people in families are replaced etc.. But here I would expect the user to be asked whether a lastname change of a person is because the family shall be renamed or because the person leaves the family.

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
>  	match{
Formatting

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
>  	action{
Formatting

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +}
Formatting

2021-11-18 09:58 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		check family.sons === null || family.sons.size == 0
Equivalent to: `family.sons?.empty` and the `?` should even be obsolete because multi-valued features should not be `null`.

2021-11-18 09:58 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +		logger.setLevel(Level.DEBUG)
Do not set logger level manually

2021-11-18 09:58 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +	def void testInsertNewFamily(TestInfo testInfo) {
You can also store the name in a `@Before` method rather than passing it to ever test method.

2021-11-18 09:58 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +		assertEquals(0, resourceAt(PERSONS_MODEL).contents.get(0).eAllContents().size)
It would be easier to understand if the persons model is matched with the expected persons model (containing only a person register).

2021-11-18 09:58 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +			family.father = FamiliesFactory.eINSTANCE.createMember => [firstName = FIRST_DAD_1; familyFather = family]
`familyFather` is set automatically when setting `family.father` as it is a bidirectional reference.

2021-11-18 09:58 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +		checkCorrectRegisters(comparisonFamilyRegister, allOf)
Why create another family register with the same contents to compare with if you have created exactly tha register before. It would be more meainingful to create the expected persons register and compare that with the actual one (applies to all test cases).

2021-11-18 09:58 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +		logger.setLevel(Level.DEBUG)
So not set log level programatically.

2021-11-18 18:39 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +	def void testInsertNewFamily(TestInfo testInfo) {
I am not sure what you mean. I do not know if `testInfo.getDisplayName()` would return the name of the actual test method (although i expect it to) or the  (at)BeforeEach method, but i do not see how this would help since i need the name in the test method and not in the (at)BeforeEach method.

2021-11-21 11:24 UTC, NeumannDirk commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/matchers/EListMultipleContainmentMatcher.xtend
> +	Iterable<? extends EObject> shouldBeContained;
Renamed to `itemsOfInterest`

2021-11-21 11:25 UTC, NeumannDirk commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/matchers/EListMultipleContainmentMatcher.xtend
> +	 * @param list items of interest
Renamed to `itemsOfInterest`

2021-11-21 11:25 UTC, NeumannDirk commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/matchers/EListMultipleContainmentMatcher.xtend
> +			description.appendText("all elements from the following list:\n")
Using now `String.format("%n")`

2021-11-21 11:25 UTC, NeumannDirk commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/matchers/EListMultipleContainmentMatcher.xtend
> +		}
fixed

2021-11-21 11:27 UTC, NeumannDirk commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/matchers/EListSingleContainmentMatcher.xtend
> +		(items as Iterable<EObject>).exists[equalsDeeply(searchedItem, options).matches(it)] == included
Removed unnecessary cast

2021-11-21 12:49 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +		logger.setLevel(Level.DEBUG)
fixed

2021-11-21 12:54 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +	def void testInsertNewFamily(TestInfo testInfo) {
```suggestion
TestInfo testInfo = null

@BeforeEach
def void insertRegister(TestInfo testInfo) { 
    this.testInfo = testInfo; ... 
}

@Test
def void testInsertNewFamily(){
    val String surroundingMethodName = this.testInfo.getDisplayName(); ....
}
```
You mean like this?

2021-11-21 13:03 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +		assertEquals(0, resourceAt(PERSONS_MODEL).contents.get(0).eAllContents().size)
The person model is now matched with an expected one in general. Therefore the Matchers (allOf, noneOf) are not needed any longer (but they are kept in the ModelMatchers.xtend). FamilyRegisters are only matched when "more difficult changes" are expected like discarding/reverting changes which were made to it during propagation.

2021-11-21 13:03 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +			family.father = FamiliesFactory.eINSTANCE.createMember => [firstName = FIRST_DAD_1; familyFather = family]
fixed

2021-11-21 13:04 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +		checkCorrectRegisters(comparisonFamilyRegister, allOf)
see above

2021-11-21 13:09 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			}
fixed

2021-11-21 13:15 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
>  	after element families::Member replaced at families::Family[father]
This is not the case. The tests fail with:
`after element families::Member inserted in families::Family[father]`
intead of
`after element families::Member replaced at families::Family[father]
     with oldValue === null && newValue !== null`
I think this is because families::Family[father] is a single attribut and not a list like families::Family[sons]

2021-11-21 13:33 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			if (!newFather.equals(oldFather)) {
- edited the `reaction EditedFather` and added `with ... && !oldValue.equals(newValue)`
- deleted the mentioned `if (!newFather.equals(oldFather))`

2021-11-21 13:50 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +				msg += ".\nPlease select one option how this conflict shall be solved."
As far as I can tell, xtend template expressions are not supported in the reactions language.

`val String s = '''Doesnt work: «newFather.toString()»'''` shows no correct xtend-Syntax-Highlighting as it would in a `.xtend` file and gives the compiler warning "This expression is not allowed in this context, sine it doesnt cause any side effects."

2021-11-21 14:06 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine createFatherInDifferentFamily(families::Member newFather, families::Member oldFather) {
I am not so sure about this. So I will give this as two different options.
Old options:
- discard changes
- replace old father
- insert father into a new family

New options
- discard changes (keep old father, delete new father)
- replace old father (insert new father, delete old father)
- insert new father into a new family and keep old father 
- insert new father, move old father in new family

Maybe we can discuss this with Thomas together with same changes in the PersonsToFamiliesReactions concerning the change options there.

2021-11-21 14:06 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			if (!newMother.equals(oldMother)) {
changed as above

2021-11-21 14:07 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +				msg += ".\nPlease select one option how this conflict shall be solved."
answer above

2021-11-24 15:05 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine evaluateFamilyDecisionForNewFather(persons::Male newFather, families::Family chosenFamily) {
Renamed to `callCorrectRoutineForNewFather`

2021-11-24 15:10 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			} else {
I do not understand the problem. This routine was created for better readability. The test `if (chosenFamily === null)` is necessary at some point for correct execution. If this is done inside the `routine createMale(persons::Male newMale)`, it would be logically the same and the family would still have to be passed to this routine for the name check.

2021-11-24 15:11 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
I would suggest to discuss this again

2021-11-24 15:14 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +				if (chosenFamily.lastName.equals(newFather.fullName.split(" ").get(1))) {
I think this should be discussed as well since a single name without whitespace could be a first name or a last name which would open the possibility for even more user interaction, especially when it comes to persons with multiple first and/or multiple last names. Until now my assumption was that names will have this scheme.

2021-11-24 15:18 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +					}
My reasoning so far was that if we want to perserve consistency and a situation pops up which can not be resolved in only one way, the correct way is to ask the user what he wants to do.

2021-11-24 15:53 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		val newFamily = create families::Family and initialize {
Since there is no possibility to return values from routines or to call other helper functions, I cannot see a way to reuse the creation of the new family. The same applies for the creation of a Member which is always the same but afterwards the new Member has to be assigned to one reference in the family (father, mother, sons, daughters). The only way could be to use a switch-variable which is passed through 2 methods to decide and then to have someting like:

//create Family
//create newMember
switch (memberPosition) {
    case 0: family.father = newMember
    case 1: family.mother = newMember
    case 2: family.sons += newMember
    case 3: family.daughters += newMember
}

... and i am not sure whether this would actually be a style-improvement but i am open for discussion

2021-11-24 15:57 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			.choices(differentLastnameOptions).windowModality(WindowModality.MODAL).startInteraction()
This is just missnamed but i fixed it to `existingFather[Message,Option,Selection].`

2021-11-24 15:59 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			newFatherMember.familyFather = family
Fixed, reduced to: `call family.father = newFatherMember`

2021-11-24 15:59 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine evaluateFamilyDecisionForNewSon(persons::Male newSon, families::Family chosenFamily) {
Renamed

2021-11-24 16:22 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
I do not know how:
- no helper methods
- no return values from routines
- only final method parameter so no call-by-ref-out-parameters

Maybe passing an empty Iterable<Integer> and adding an element can work but I cannot figure out the syntax if this is possible. If I missed something please let me know but so far I do not know how and neither did Thomas.

2021-11-24 16:55 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
I understand what you mean, following my own reasoning, the user should be asked if the family should be renamed or if the person is moved to a new Family or in a different existing family. I will wait with implementing it until we have discussed this since it would be obsulete if we decide that this kind of change is made only in the families model just as other changes you commented above

2021-11-24 17:02 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		check family.sons === null || family.sons.size == 0
Now only using `.empty`

2021-11-24 17:02 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +}
fixed

2021-11-24 17:02 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
>  	match{
fixed

2021-11-24 17:02 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
>  	action{
fixed

2021-11-24 17:05 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +		logger.setLevel(Level.DEBUG)
removed

2021-12-02 10:46 UTC, tsaglam commented
There are a lot of outdated discussions above, @NeumannDirk can you resolve all change requests that are already fixed? This makes it easier for me to see what is still left to change. It gives me a bit more clarity when I make my review here.

2021-12-16 12:44 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
>  	after element families::Member replaced at families::Family[father]
Then it does not make sense that this kind of statement is allowed, i.e., it is a bug in the language, which we have to document.

2021-12-16 13:49 UTC, HeikoKlare requested changes
The code looks much better after recent changes. It is, however, hard to re-review the code after most of the comments have been closed without giving an answer to the comment. That required a cumbersome re-investigation of all the issues to see whether they have been solved, became obsolete, or have been ignored.

There are some new but in general minor issues that came up with the recent changes and should be easy to fix. A quite larger problem to fix is the handling of person names, as this is not implemented correctly and, in particular, not covered by any test cases right now.
In addition, some of the old issues have been marked as resolved but are actually not.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine replaceFather(families::Member newFather, families::Member oldFather) {
These are, from a logical point of view, two routines: One that creates a person for the new father and one that puts the old father into a new family. Please separate the logic accordingly.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			newFamily.father = oldFather
This statement should be in the upper family creation block.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			familyRegister.families += newFamily
Put into an `update familyRegister` block instead.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine replaceMother(families::Member newMother, families::Member oldMother) {
Same comments as for replacing father apply.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call createMale(newValue, newValue.familyFather)
Use `affectedEObject` instead of `newValue.familyFather` instead. The latter may not be correct anymore in the moment the change is processed.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call createFemale(newValue, newValue.familyMother)
see above

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call createMale(newValue, newValue.familySon)
see above

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call createFemale(newValue, newValue.familyDaughter)
see above

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine changeFullNameFromFirst(families::Member member) {
This routine's name is wrong: it does simply `updatePersonName`, no matter whether the first or the last name was changed.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine changeFullNameFromLast(families::Family family) {
It would be even more uniform to use the `changeFullNameFromFirst` routine (which is actually an `updatePersonName` routine) for each of the family members. Then the error-prone string splitting can even be avoided.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			createMember(newPerson, parentOrChildSelection == 1)
To make this readable and less error prone, at least use `parentOrChildSelection == parentOrChildOptions.indexOf("Child")`.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			val String newPersonLastname = newPerson.fullName.split(" ").last
There is no proper handling for persons not having one (or more) first names and one last name separated by a whitespace yet (as already mentioned in the last review). With the current implementation, a person with name `X` will be inserted with firstname `X` into a family with name `X`, which is wrong and will result in an inconsistent state.
Please add a proper validation of the name and then decide what happens if a person has a name only consisting of a single word (or even none). If we allow empty first or last names, the options would be to either use a single word as either first or last name (but only as one of them) or to ask the user which of them it is supposed to be.

If I am not mistaken, there is no test case for any of the situations that can occur with a name: being empty, having only one word, having more than two words. All tests give names consisting of two words, is that correct? Then a bunch of according test cases must be added.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
I would still propose to put this into a helper method (I think I have placed that comment already in the last review). With "helper methods" I mean simple static methods in a separate utility class. Then you can also separate this routine into two ones, specific for whether its about adding a child or a parent instead of mixing up the logic.

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +				}
I don't get this. The families have to be filtered for those which have a place for the person to be added. Here, it is decided on whether the user can select a family depending on whether any of the potential families fits. The user can then, however, again select from all families, even those in which the person does not fit.
This has to be fixed and this situation must also be covered by a test case (as it is apparently not).

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		call {
use `update newMember` instead, as this is not a call

2021-12-16 13:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine editLastnameRemovePerson(persons::Person person, String fullName) {
Why are members deleted and created just because of a name change?

2021-12-16 13:49 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +	TestInfo testInfo = null
It is sufficient to just store the `testName` here. This can then directly be referenced in every test case without extracting the information in every test case anew.

2021-12-16 13:49 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +		userInteraction.addNextSingleSelection(1)
Please replace these magic number selections by proper selections using methods such as `addNextSingleSelection`, like I have explained in the last review.

2021-12-16 13:57 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
>  	after element families::Member replaced at families::Family[father]
In the current version the code looks like this:
`
reaction EditedFather {
	after element families::Member replaced at families::Family[father]
		with oldValue !== null && newValue !== null && !oldValue.equals(newValue)
	call replaceFather(newValue, oldValue)
}
reaction CreatedFather {
	after element families::Member replaced at families::Family[father]
		with oldValue === null && newValue !== null
	call createMale(newValue, newValue.familyFather)
}
reaction DeletedFather {
	after element families::Member replaced at families::Family[father]
		with oldValue !== null && newValue === null
	call deletePerson(oldValue)
}
`
If I replace "replaced at" with "inserted in" then "The method or field oldValue is undefined".
If I just do
`
reaction EditedFather {
	after element families::Member inserted in families::Family[father]
	call foo(newValue)
}
`
then there is no compile time error. If I understand this correctly (that "inserted in" is only for collections) there should be an error maybe

2022-01-14 17:30 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +		userInteraction.addNextSingleSelection(1)
Do you mean by adding these numbers as e.g. static ints to just give them a name, like this:
```suggestion
      private static int CHOOSE_PARENT = 0
      private static int CHOOSE_CHILD = 1
      private static int FIRST_EXISTING_FAMILY = 1
      def foo(){ ...
		userInteraction.addNextSingleSelection(CHOOSE_PARENT)
		// Mother
		userInteraction.addNextSingleSelection(CHOOSE_PARENT)
		// Son in existing Family
		userInteraction.addNextSingleSelection(CHOOSE_CHILD)
		userInteraction.addNextSingleSelection(FIRST_EXISTING_FAMILY)
		// Daughter in existing Family
		userInteraction.addNextSingleSelection(CHOOSE_CHILD)
		userInteraction.addNextSingleSelection(FIRST_EXISTING_FAMILY)
```

or do you mean using the possibilities to pass "lambdas" as decision functions, which are then filled with the magic number, like this:

```suggestion

		val boolean preferParent = true;
		val parentChildResponseBuilder = this.getUserInteraction()
			.onMultipleChoiceSingleSelection(
				(MultipleChoiceInteractionDescription m) => [return m.title.equals("Parent or Child") ]
			)
		parentChildResponseBuilder.respondWithChoiceAt(preferParent ? 0 : 1);
	
		//addFather (+automatic creation of new family)
		PersonRegister.propagate [
			persons += helper.createNewMale => [fullName = "Max Muster"]
		]	
```

I think the second version might be a little bit overkill but to be really sure: Which one do you mean?

2022-01-14 22:15 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		call {
Inside an update block one cannot call other routines. So I would have to copy the code, which would lead to duplicated code since I am using this `setMemberFirstName` routine twice. Should I inline the code at the two spots were I currently call the routine?

2022-01-14 22:29 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine editLastnameRemovePerson(persons::Person person, String fullName) {
I thought of this as a handy trick. Deleting and recreating the member to avoid moving it around since the handling of correspondences and asking for userinteractions seemed quite error-prone to me... However, I realised this might cause problems - espacially if there are more then two metamodells and potential ConsequentialChanges.
So now it is done like this:

If person.fullname is changed
    change firstname of corresponding member
    If lastname has to be changed
        if renamed member is alone in the family
            simply rename the family
        else
            move renamed member to a different family using the member-insertion-logic by adding some 
            an optional parameter to indicate that corresponding member already exists

I hope this logic is ok. I will also add tests for the case that the member is alone in his family and resolve this conversation as soon as I did so.

2022-01-14 22:49 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +				}
```suggestion
			if (isChild) {
				askUserForFamily = !matchingFamilies.empty
			} else {
				if (newPerson instanceof Male) {
					matchingFamilies = matchingFamilies.filter[it.father === null]					
				} else {
					matchingFamilies = matchingFamilies.filter[it.mother === null]
				}
				askUserForFamily = matchingFamilies.size > 0
			}
```

Sorry, this behaviour was never intended. I will also try to add tests (probably using the ResponseBuilder) to check if a family is a choosable option which should not be one and resolve this conversation as soon as I did so.

2022-01-14 23:09 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
I did not thought of this as mixing parent and children logic, since it only effects the possibly selected families. However, this is a side product of trying to avoid duplicated code, when I thought "helper methods" mean helper methods within the reactions language. I will extract the creation and filling of `val Collection<String> whichFamilyOptions` into a xtend helper class and split this method into a version for parents and children and resolve this conversation as soon as I did so.

2022-01-14 23:16 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			val String newPersonLastname = newPerson.fullName.split(" ").last
Concerning the first paragraph: This behaviour is just as intended in consultation with Thomas Kühn.
Concerning the first paragraph: There is one test, covering the case for one name and for more than two names. The case of an empty name is not yet covered. I wlll add a test to check if an exception is thrown and resolve this conversation as soon as I did so.

2022-01-17 12:39 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +		userInteraction.addNextSingleSelection(1)
I actually mean the second one, as the first one is quite error prone. There could be any kind of interaction asking for a selection and the first implementation would match them, while the second actually checks whether it is the appropriate interaction to respond to. So they are different from an expressiveness point of view, which is why the second is not "overkill". If you mean that the code is quite verbose, this can be optmized using Xtend:
```Xtend
userInteraction.onMultipleChoiceSingleSelection[title.equals("Parent or Child")].respondWithChoiceAt(if (preferParent) 0 else 1)
```

2022-01-21 10:35 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		call {
There is no routine call within the marked `call` block. The comment refers to (or was supposed to refer to) the second `call` block (not the one with `setMemberFirstName`), in which no other routines are called. However, in contrast to my initial comment, it should be an `update family` rather than an `update newMember`, because the changes there affect the family.

2022-01-26 21:00 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine replaceFather(families::Member newFather, families::Member oldFather) {
Concerning the first part:
I think I assumed last time that this was about using `newFather.familyFather.eContainer` instead of `newFather.eContainer.eContainer`. Anyway it is replaced by:
`val FamilyRegister familyRegister = oldFamily.eContainer as FamilyRegister`

Concerning the second part: This is now separated

2022-01-26 21:01 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			newFamily.father = oldFather
Done

2022-01-26 21:04 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call createMale(newValue, newValue.familyFather)
Done wherever possible

2022-01-26 21:38 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine changeFullNameFromFirst(families::Member member) {
There is the corresponding `routine changeFullNameFromLast(families::Family family)`. Both are triggered from different objects (member or family) and they also do different things. E.g. `routine changeFullNameFromLast(families::Family family)` changes the fullnames of multiple persons and `routine changeFullNameFromFirst(families::Member member)` only of one. I think using one for both is not really a good idea.

If you are just talking about the wording this is something different. I can rename them in something like "updateFirstNameOfPerson" and "updateLastNameOfPersons".

2022-01-26 22:22 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine changeFullNameFromFirst(families::Member member) {
```suggestion
routine updatePersonName(families::Member member, persons::Person person) {
	match {
		val retrievedMember = retrieve families::Member corresponding to person
		val retrievedPerson = retrieve persons::Person corresponding to member
	}
	action {
		call {
        		notNullMember = member ?: retrievedMember
        		notNullPerson = person ?: retrievedPerson
        		val family = notNullMember.familyFather ?: notNullMember.familyMother ?: notNullMember.familyDaughter ?: notNullMember.familySon
			notNullPerson.fullName = notNullMember.firstName + " " + family.lastName
		}
	}
}
```

2022-01-26 22:30 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine changeFullNameFromLast(families::Family family) {
see above

2022-01-26 22:30 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			createMember(newPerson, parentOrChildSelection == 1)
done

2022-01-27 10:45 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		call {
code has changed -> should be resolved

2022-01-27 10:46 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine changeFullNameFromFirst(families::Member member) {
Implemented the version from the EDIT comment - therefore it should be resolved

2022-01-31 12:03 UTC, HeikoKlare requested changes
The last commits have messed up several things, which is why I provide a first review with some rather general comments that need to be discussed and/or addressed before making a potential further in-depth review.

Regarding functionality, I do not understand the behavior in case a person's last name changes. In addition, there are several pieces of (potentially unintended) dead code, which are written in a way that one cannot understand what the code was actually supposed to do. Finally, the handling of persons having a name that consists of a single work is still "wrong", i.e., it is at least inconsistent with the behavior in the opposite transformation direction.

Regarding code style, there are several flaws for which I have placed comments. Most important, please use method, parameter and variable names that make sense in the context in which they are used and that make it easy to understand what happens. In case this is really not possible, add some documentation. Some parts of the code are really hard to understand, because either the used names do not explain what happens, thus one needs to read and comprehend the implementation, or the used names are even wrong, i.e., inconsistent with what a method or variable actually is or does.

2022-02-04 11:59 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +		return family.eContainer as FamilyRegister
```suggestion
       /** Returns the eContainer of a Family casted as FamilyRegister if it actually is one.
	 *  Returns null if the Family is contained in any other type of eContainer. 
	 */
	def static FamilyRegister tryGetFamilyRegister(Family family) {
		return if (family.eContainer instanceof FamilyRegister)	family.eContainer as FamilyRegister else null
	}
```

Is this ok and then I check inside the Reactions if the return value is not null. Or should I throw Exceptions?

2022-02-04 12:02 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +//Firstname changed so only the corresponding {@link Person} is effected.
Deleted

2022-02-08 11:31 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +class FamiliesToPersonsHelper {
Moved functions to FamiliesUtil which has `@Utility` annotation, made this class final, added private constructor, fixed one bug and deleted `FamiliesToPersonHelper.xtend`

2022-02-08 11:35 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			val family = getFamily(member)
Done for all extension methods

2022-02-08 11:39 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend
> +	TestInfo testInfo = null
Done

2022-02-08 11:40 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call getMembers(affectedEObject).forEach[updatePersonName(it)]
Done

2022-02-08 12:04 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		val personsRegister = retrieve persons::PersonRegister corresponding to family.eContainer
Done

2022-02-08 12:11 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		add correspondence between familyRegister and personRegister tagged with "PersonRegister-FamilyRegister"
Concerning the whole tagging, this was not suppossed to be pushed. I had some problems with missing correspondencies, so this was just a test on the fly which I realized later that I pushed it by accident but you already commented. The tagging of correspondencies as well as the check of how many correspondences exist will be deleted.

2022-02-08 12:13 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	new() {}
Done

2022-02-08 12:17 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +		return returnString
Now uses `StringBuilder`

2022-02-08 12:18 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		add correspondence between newPerson and newMember tagged with "Person-Member"
See above

2022-02-08 12:18 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		}
See above

2022-02-08 12:18 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
See above

2022-02-08 12:20 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			if (numberOfMembers == 1) {
Replaced by utility method

2022-02-08 12:22 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		call {
Changed

2022-02-08 15:25 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	def static Iterable<Family> getMatchingFamilies(Person newPerson, FamilyRegister familyRegister, boolean insertChild){
Like this?
```suggestion
        /** Returns all families from the {@code familyRegister} with the same last name as the {@code newPerson}.
	 */
	def static Iterable<Family> getMatchingFamilies(FamilyRegister familyRegister, Person newPerson) {		
		val String newPersonLastname = newPerson.fullName.split(" ").last		
		return familyRegister.families.filter[it.lastName.equals(newPersonLastname)]
	}
	
	/** Returns all families from the {@code unfilteredFamilies} which have a parent of the same sex as the {@code newPerson}.
	 */
	def static Iterable<Family> getFamiliesWithoutParent(Iterable<Family> unfilteredFamilies, Person newPerson) {		
		return unfilteredFamilies.filter[if(newPerson instanceof Male) it.father === null else it.mother === null]
	}
```

2022-02-08 15:37 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	def static Family askForFamilySelection(UserInteractor userInteractor, Person newPerson, Iterable<Family> selectableFamilies) {
- renamed method to `askUserWhichFamilyToInsertTheMemberIn`
- added comment

2022-02-10 08:43 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		call {
done

2022-02-13 11:08 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			if (newPerson instanceof Male) {
All occurrences of `instanceof` are replaced with `switch`-statements.

2022-02-14 11:33 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine applyNewLastnameToMember(persons::Person person, String newLastname) {
This method is deleted and replaced by a method called `reactToLastnameAndPositionChanges` since now the position of a member inside a family can also be changed during renaming.

2022-02-14 11:38 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			moveExistingMemberToDifferentFamily(person, isChild, member)
In consultation with Thomas, it is now permitted to change the position of the member. A new kind of user interaction is added to do so. This one is handeled as the parent-child-interaction during insertion but with an altered description to give more context information to the user.

2022-02-14 22:02 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		}
This behaviour is now changed such that a person "X" is now inserted as member "X" into a family "". The opposite direction will be added as well such that a persons fullname is reconstructed as "X" and not ("X" + " "). Although family lastnames will be restricted zu only non-null, non-empty names.

2022-03-02 08:03 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +}
done

2022-03-02 08:04 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		createMale(newValue, affectedEObject)
This is now splitted in two cases. One in which the member which becomes the newFather existed before and on in which it did not.

2022-03-02 08:07 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +	call createMale(newValue, affectedEObject)
Splitted in two cases you named. Should be resolved.

2022-03-02 09:56 UTC, HeikoKlare requested changes
See detailed comments. There are some repetitive issues and some unadressed issues from the last review.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		check optionalCorrespondingPerson.empty
Why not simply make a `require absence of` check here?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		check !optionalCorrespondingPerson.empty
Why not simply make an ordinary `retrieve`? This is exactly how a `retrieve` behaves: If there is no such element, abort routine execution.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +reaction DeletedAndRemovedSon {
Why have one delete reaction for each containment of a member and not simply have one reaction for the deletion of a member that deleted the corresponding person?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine ifExistingMember_updateCorrespondencesMale(families::Member newFather, families::Family newFamily) {
Bad naming: This method does somthing for fathers of families, but the routine name does refer to male instead of fathers and does not state what this "update" means. In particular, it does not only update a correspondence but also changes the name of the corresponding person. Why not precisely say `updateNameAndCorrespondenceOfMemberMadeFather` or the like?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine ifExistingMember_updateCorrespondencesFemale(families::Member newMother, families::Family newFamily) {
Bad naming: see above

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		check !optionalCorrespondingPerson.empty
Why not simply make an ordinary `retrieve`? This is exactly how a `retrieve` behaves: If there is no such element, abort routine execution.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
Why do this in the action rather than the match?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
Why do this in the action rather than the match?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine existingMemberBecomesNewParent_updateCorrespondences(families::Member newMember, persons::Person correspondingPerson, families::Family newFamily, families::Family oldFamily) {
Bad naming: see above

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
Why are empty families only removed after moving away parents, but not after moving away children? Have I missed some constraint that ensures that families must have either a father or mother that makes this reasonable?
Then it would also be helpful to a specific reusable routine for removing empty families.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine updateCorrespondencesAfterMemberBecameSon (families::Member insertedChild, families::Family newFamily) {
Bad naming: see above

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine updateCorrespondencesAfterMemberBecameDaughter (families::Member insertedChild, families::Family newFamily) {
Bad naming: see above

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
Why do this in the action rather than the match?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine updatePersonFamilyCorrespondence (families::Member insertedChild, persons::Person correspondingPerson, families::Family newFamily) {
Bad naming: see above

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine updatePersonFamilyCorrespondence (families::Member insertedChild, persons::Person correspondingPerson, families::Family newFamily) {
And why pass the `correspondingPerson` here? You can also retrieve it in this routine and make the signature more simple.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
Why have this in the action rather than the match?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +	private new() {}
The `@Utility` annotation already creates a private constructor.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			var Family chosenFamily = if (matchingFamilies.empty) null else askUserWhichFamilyToInsertTheMemberIn(userInteractor, insertedPerson, matchingFamilies)
Why are these `var` instead of `val`?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			if (chosenFamily === null) {
Why have `null` as a magic key here? Why not simply put the chosen family identification into the `else` branch for the case that matching families exist.

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
See comments for `createChild`

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
Why throw `IllegalArgumentExceptions`? The checked values are not arguments, so probably this is rather an illegal state?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
See comments for `createChild`

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine insertExistingMemberIntoNewFamilyAsChild(persons::Person renamedPerson, families::Member correspondingMember) {
Why pass the `correspondingMember` instead of retrieving it?

2022-03-02 09:56 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		//correspondence between newPerson and member does already exist
What is the `newPerson`?

2022-03-02 10:22 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +			familyRegister.families += newFamily
If `getRegister` returns `null`, an `UnsupportedOperationException` will be thrown to indicate that this behaviour is not implemented yet.

2022-03-02 10:33 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		ifExistingMember_updateCorrespondencesMale(newValue, affectedEObject)
On 2021-12-16 you wrote in a conversation:
> These are, from a logical point of view, two routines: One that creates a person for the new father and one that puts the old father into a new family. Please separate the logic accordingly.

So starting from there, i assumed that it is prefered behaviour that in the case of a replacement of a parent this parent is not deleted, but just removed to a new family to keep it availiable for further handling. From where it can be deleted then if this is that desired result. Also if the intention was to delete the parent it also could be deleted first and then the enw parent is inserted at this position. This seemed reasonable to me so far. Concerning your last comment on this code snippet, I understood this as critique on handling the removal of the old parent to a new family and the insertion of the new parent in the same routine which is why I seperated this as two (1 + 1 out of 2) seperate routines.

Please let me know if I should alter this behaviour to always deleting the replaced parant automatically.

2022-03-02 10:37 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	 * 	@param person Person to retrieve the firstname from.
Seemes correctly formatted when I open it in eclipse. I removed all blank lines. Maybe this fixes it.

2022-03-02 10:44 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	def static boolean doesUserPreferChildOverParent(UserInteractor userInteractor, Person newPerson) {
Done as suggested

2022-03-02 10:45 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +		return [Family p|p.lastName.equals(newPersonLastname)]
`p` stands for parameter but is now renamed to `family`

2022-03-02 10:58 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		check optionalCorrespondingPerson.empty
changed implementation

2022-03-02 11:04 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		check !optionalCorrespondingPerson.empty
Oh I somehow had in mind that this throws an exception if no correspondence is availiable. Changed it

2022-03-03 14:11 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		with oldValue.eContainer === null
This is not correct. If this is supposed to be the case, then there is an error in the reactions language. Following your comments on the multiple deletion-reactions, I replaced the 4 different deletion-reactions by the following one.
```suggestion
reaction DeletedMember {
	after element families::Member deleted
		with affectedEObject.eContainer === null
	call deletePerson(affectedEObject)
}
```
So far, so good. But if I now remove the check like so:
```suggestion
reaction DeletedMember {
	after element families::Member deleted
	call deletePerson(affectedEObject)
}
```
errors in the tests occur, everytime that the last member from a family is moved (not deleted) to a different family. So the only way I see at the moment is to check if the member was actually deleted which means it has no eContainer or if it was just moved elsewhere and therefore has automatically a new eContainer.

2022-03-03 14:13 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +reaction DeletedAndRemovedSon {
Replaced the four by one for all four

2022-03-03 14:37 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine ifExistingMember_updateCorrespondencesMale(families::Member newFather, families::Family newFamily) {
This routine does not only do something for fathers, but for member which become a father as you stated. This can also be sons and the corresponding persons are therefore always Males which I thought to capture by naming it such that it says that informations concerning this Male (the correspondences and the name) are updated. You suggestion sounds like the name of the father-made member is changed which is not the case. 
Therefore, I would suggest the name `ifExistingMember` to keep the idea that one can see right away that only one of the two routines in the reaction are completely executed and then add `BecomesFather_` to describe the situation and use this instead of `MemberMadeFather` and then add  `_updateNameAndCorrespondences` (multiple correspondences since one is deleted and another is created) and then `OfCorrespondingMale`, since only Males are allowed and those are the ones who are updated. 
So `ifExistingMemberBecomesFather_updateNameAndCorrespondencesOfCorrespondingMale`
This seems rather long but it contains all the information you mentioned.

Accordingly:
`ifExistingMemberBecomesMother_updateNameAndCorrespondencesOfCorrespondingFemale` for mothers
`existingMemberBecomesParent_updateNameAndCorrespondencesOfCorrespondingPerson` as the routine which are called from both to indecate that one can now be certain that it is in fact an existing member and that this routine can be used for both genders.

2022-03-03 15:18 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
Introduced the function `checkMale` which does this check and either returns null or throws an exception as before. The idea and also necessity behind throwing an exception and not only checking with a boolean value is that not doing so will result in a former mother becoming a father and ending the routine right away without error. Therefore, a change which be made which is not valid and names and correspondences of the corresponding (female) person wont change.

2022-03-03 15:19 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
see above, but with `checkFemale`

2022-03-03 15:22 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine ifExistingMember_updateCorrespondencesMale(families::Member newFather, families::Family newFamily) {
Regarding the passing over of the `correspondingPerson`, I thought that passing over this parameter is better than re-retrieving it from the model. I changed this approach to always re-retrieve the values instead of passing them around

2022-03-03 16:08 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
This was actually wrong and not yet covered by a test case. Accordingly, new tests and a routine called call `deleteFamilyIfEmpty(families::Family family)` have been addded.

2022-03-03 16:08 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
see above

2022-03-03 16:08 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
see above

2022-03-03 17:00 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +routine updateCorrespondencesAfterMemberBecameSon (families::Member insertedChild, families::Family newFamily) {
I renamed it to `existingMemberBecameSon_updateNameAndCorrespondencesOfCorrespondingMale`
since this, as explained above includes all information about the current situation and what will happen next.
The deletion of the old family if it is empty is not mentioned in this name but i would argue that this can be seen as an overall consistency preservation which has not to be mentioned explicitely each time.

2022-03-03 17:05 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		}
now in the match block

2022-03-03 17:06 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +	private new() {}
deleted constructor

2022-03-03 17:08 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			var Family chosenFamily = if (matchingFamilies.empty) null else askUserWhichFamilyToInsertTheMemberIn(userInteractor, insertedPerson, matchingFamilies)
Replaced all `var` with `val`

2022-03-03 17:11 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
Done as suggested

2022-03-03 17:11 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			if (chosenFamily === null) {
Done as suggested

2022-03-03 17:22 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			if (chosenFamily === null) {
`askUserWhichFamilyToInsertTheMemberIn` can return `null` if the user chooses to insert the corresponding member into a new family. Therefore `if (chosenFamily === null)` has to be checked anyway. An alternative might be:

```suggestion
			if (matchingFamilies.empty) {
				createChildInNewFamily(insertedPerson)
			} else {
			        val Family chosenFamily = askUserWhichFamilyToInsertTheMemberIn(userInteractor, insertedPerson, matchingFamilies)
			        if (chosenFamily === null) {
			                createChildInNewFamily(insertedPerson)
			        } else {
			                createChildInExistingFamily(insertedPerson, chosenFamily)
			        }
			}
```

I am not sure if this is better style. Let me know if you think so and I commit this version.

2022-03-03 17:39 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
- Changed to `IllegalStateException`
- extracted logic to helper extension method
- calling the chek in the `match`-block

2022-03-03 18:17 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine reactToLastnameAndPositionChanges(persons::Person renamedPerson, String oldFullname) {
A position change occurs for example when a person - whose corresponding member was a child before - is renamed and the user wants the person not only to change its family but also its position which in this example means the foramer child becomes a parent in the new family. Although this is much less real world applicable, this can also be applied to former parents which become children again.

2022-03-03 19:12 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		val correspondingMember = retrieve families::Member corresponding to renamedPerson
Added `with [...] && !oldValue.equals(newValue)` to the reaction

2022-03-03 19:28 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			val boolean wasChildBeforeRenaming = if (renamedPersonIsMale) correspondingMember.familySon === oldFamily else correspondingMember.familyDaughter === oldFamily
- replaced the if-else with an or-operator
- replaced `renamedPersonIsMale` with an switch.operator with typa guard further down
- if a person is a child in the families model might be an utility method but is here not applicable since here the question is wether it was a child before which could have changed during the renaming process

2022-03-03 19:29 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
See answer for `createChild`

2022-03-03 19:29 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
See answer for `createChild`

2022-03-03 19:31 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine insertExistingMemberIntoUserChosenFamilyAsChild(persons::Person renamedPerson, families::Member correspondingMember) {
Now retrieved instead of passed

2022-03-03 19:31 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine insertExistingMemberIntoUserChosenFamilyAsParent(persons::Person renamedPerson, families::Member correspondingMember) {
Now retrieved instead of passed

2022-03-03 19:35 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine insertExistingMemberIntoExistingFamilyAsParent(persons::Person renamedPerson, families::Member correspondingMember, families::Family familyToInsertInto) {
Now retrieved instead of passed

2022-03-03 19:37 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		//correspondence between newPerson and member does already exist
comment changed updated to 
"//correspondence between renamedPerson and correspondingMember does already exist"

2022-03-03 19:47 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine insertExistingMemberIntoExistingFamilyAsChild(persons::Person renamedPerson, families::Member correspondingMember, families::Family familyToInsertInto) {
Now retrieved instead of passed

2022-03-03 19:47 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +		//correspondence between newPerson and member does already exist
comment changed updated to
"//correspondence between renamedPerson and correspondingMember does already exist"

2022-03-03 19:48 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	private new() {}
removed constructor

2022-03-04 11:51 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine insertExistingMemberIntoExistingFamilyAsChild(persons::Person renamedPerson, families::Member correspondingMember, families::Family familyToInsertInto) {
Now retrieved instead of passed

2022-03-05 15:53 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +routine reactToLastnameAndPositionChanges(persons::Person renamedPerson, String oldFullname) {
In consultation with Thomas, I also renamed it to `reactToLastnameAndFamilyRoleChanges`

2022-03-09 08:25 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		ifExistingMember_updateCorrespondencesMale(newValue, affectedEObject)
This was my comment:
> Why is the behavior of replacing a father different from removing a father w.r.t. what happens to the old father? In case a new father is inserted, the old one is moved to another family. In case no new father is inserted, the old one is deleted. This seems to be inconsistent. I would propose to unify that behavior and than simply have one routine that handles father removals (no matter if a new one was inserted or not) and a father insertion (no matter if there was an old father or not) to ease maintainablity, improve comprehensibility and unify the behavior.

I was particularly asking for an explanation, not necessarily for a modification. Replacing a father in a family is, from a conceptual point of view, always strange, so neither solution will be "perfect". Just the movement of the old father to a new family introduces complexity which may not be necessary and which is not required when simply deleting it. But maybe just leave it as it is.

2022-03-09 08:30 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		with oldValue.eContainer === null
What do you mean by "errors in the tests occur"? And under which conditions is there a delete change in case a member is moved to another family? If this is actually the case, this would be a severe bug in the change monitor (as it should only create delete changes if an element is not inserted somewhere else again), which should lead to failures in many other cases as well. So it would be interesting to have a regression test for that to fix it.

2022-03-09 08:43 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		ifExistingMember_updateCorrespondencesMale(newValue, affectedEObject)
Maybe one good argument for moving the old parent away is this: If the old parent would be deleted, the corresponding person in the persons register would be deleted as well. So the creation (or definition if just moving) of a new parent in the families model leads to the deletion of a person in the persons model. It might be contra-intuitive for an user that creating something on the onw side leads to an deletion on the other side. 
Also if we consider more than two models, the deletion in the persons model might trigger a new consequent change in the third model. To be fair the creation of the new family could do so as well but I think this is always less invasiv since a family is more or less just a container for its members.

2022-03-09 09:34 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		with oldValue.eContainer === null
There are actually multiple (10!) tests that will fail. These two:
- [`FamiliesPersonsTest::testReplaceMotherWithExistingPreviouslyLonlyDaughter`](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend#L1052-L1088)
- [`FamiliesPersonsTest::testSwitchFamilyDifferentPositionLonlySonToFather`](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend#L1131-L1167)

will already fail when the family register is compared with the existing one. The differences here are rather strange since the only difference is that the family from which the lonly member was removed still exists. It seems like the lonly member is deleted (so the corresponding person is deleted), then the old parent is moved away and now the routine for the creation of a new father is triggered since no corresponding person exists anymore and therefore the oldfamily of the new parent stays there empty which leads to some strange errors probably resulting from the wrong order of the families which I mentioned in the issue that was closed again since this is EMF-Compare logic.

The other eight:
- `testExceptionSexChanges_AssignFatherToMother`
- `testReplaceMotherWithExistingDaughter`
- `testExceptionSexChanges_AssignMotherToFather`
- `testReplaceMotherWithNewMember`
- `testReplaceFatherWithExistingSon`
- `testReplaceFatherWithNewMember`
- `testReplaceMotherWithExistingMother`
- `testReplaceFatherWithExistingFather`

will pass the families model check but then fail in the persons model check because the old parent is moved to its new familiy an then afterwards (although the member is actually not deleted) the DeltedMember reaction is triggered and the corresponding person is deleted which is not only not intended, but also breaks consistency.

2022-03-09 10:04 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		with oldValue.eContainer === null
Well, then it sounds like the behavior is due to the transformations modifying their source model. The Reactions and the change monitor behave as expected, but you have to be really careful when changing the source model of a transformation (and usually avoid it). This is another argument against moving around a father that has been removed from its family, as discussed in another thread.

2022-03-09 10:34 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		ifExistingMember_updateCorrespondencesMale(newValue, affectedEObject)
Well, it's not about _creating_ something, but about _replacing_ something, and if you replace something in a containment relation it should be clear that this removes the thing that was contained there before. 
Transitive propagation is a mechanism that should even independent from that, at least I do not understand how far transitive progagation is specific in this case. 
As mentioned in another thread, a further problem is that modying the source model in a transformation easily leads to issues, so you should avoid that whenever possible.

2022-03-09 10:36 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			if (chosenFamily === null) {
Alright, it was not clear to me that the `askUser...` method may also deliver `null` as a magic key. Then it's probably best to keep the impementation as it was before.

2022-03-09 10:47 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +	}
Why do these methods return a `boolean`? Actually, they only return `true` and throw an exception otherwise, so why have a return value at all?

2022-03-09 10:47 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/META-INF/MANIFEST.MF
> + org.apiguardian
Are all these dependencies really necessary?

2022-03-09 10:47 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
I do still not understand why this should be an `IllegalArgumentException`. This exception is thrown by a method receiving an argument it is not able to handle. This makes sense to throw if the caller is not expected to pass such a value to the method. In this case, however, a name that cannot be handled is not an illegal argument, because it is simply a model state that cannot be handled (neither by the caller nor by the callee).

2022-03-09 12:01 UTC, HeikoKlare requested changes
I have some minor comments remaining and there are some ongoing discussions from the previous review.

2022-03-10 12:19 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/META-INF/MANIFEST.MF
> + org.apiguardian
These dependences were created automatically when I used `@ParameterizedTest` so I thought they are necessary, but deleting some of them turned out to be no problem.

2022-03-10 12:21 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	}
see answer above

2022-03-10 12:22 UTC, NeumannDirk commented on tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/persons2families/PersonsToFamiliesTest.xtend
> +	}
Fixed

2022-03-10 12:25 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamilies.reactions
> +			}
Ok I see your point. I would have said that renaming is a method in which an illegal argument is passed. I will then just go with the `IllegalStateException` exception and delete the other check-method

2022-03-10 12:46 UTC, NeumannDirk commented
> I have some minor comments remaining and there are some ongoing discussions from the previous review.
I have check your comments and two final questions:

1. Should the check-methods return booleans to use them inside the match blocks or should the be voids and then be in the action block or is there a way of calling procedures inside a match block?
2. Concerning the problems with the manipulation of the source (family) model during consistency preservation: Should I keep it this way and move the old parent to a new family or should I remove this functionality and let it be deleted instead?

The other problems should be resolved, changes are pushed.

2022-03-11 11:49 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +	}
First, a method provides some functionality and should, in general, do it in a way independent from where it is used. Thus having a specific return value because a method is used somewhere in a specific way may not be the best argument.
Second, why should the return value affect where the method can used?

2022-03-11 11:52 UTC, HeikoKlare commented
Regarding 1.: See my comment above. There is not reason (I can see) why a return value of a method should depend on its usage.
Regarding 2.: I would be in favor of removing the functionality for moving a parent, because I do not see a benefit from a semantic perspective while it introduced additional (potentially unnecessary) funtionality while it also contains unwanted behavior (changing the source model).

2022-03-15 20:16 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +	}
see commit [f9aaa61](https://github.com/vitruv-tools/Vitruv/pull/477/commits/f9aaa617ae56e6f506a66fffeeb076d998af7e94)

2022-03-15 20:54 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/persons2families/PersonsToFamiliesHelper.xtend
> +	}
also done for other occurences of this issue in

- commit [7768e93](https://github.com/vitruv-tools/Vitruv/pull/477/commits/7768e934fa3265bd13d12ae868ea30d12b76c048)
- commit [21a0377](https://github.com/vitruv-tools/Vitruv/pull/477/commits/21a037746cd02282f6978426a565d690b2bfaa68)

2022-03-15 20:55 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersonsHelper.xtend
> +	}
also done for other occurences of this issue in

- commit [7768e93](https://github.com/vitruv-tools/Vitruv/pull/477/commits/7768e934fa3265bd13d12ae868ea30d12b76c048)
- commit [21a0377](https://github.com/vitruv-tools/Vitruv/pull/477/commits/21a037746cd02282f6978426a565d690b2bfaa68)

2022-03-15 20:56 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		ifExistingMember_updateCorrespondencesMale(newValue, affectedEObject)
Deleted the functionality of keeping the old parent and moving it to its own new family.
See commit [d43b88c](https://github.com/vitruv-tools/Vitruv/pull/477/commits/d43b88c60fc17d1ec0075633750c6fc1e814cc60)

2022-03-15 21:07 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		with oldValue.eContainer === null
After deleting the functionality of keeping the old parent and moving it to its own new family (see [d43b88c](https://github.com/vitruv-tools/Vitruv/pull/477/commits/d43b88c60fc17d1ec0075633750c6fc1e814cc60)), this error stays. It now only occurrs less often. The four remaining failing tests without the `with affectedEObject.eContainer === null` check are:

- [`FamiliesPersonsTest::testReplaceMotherWithExistingPreviouslyLonlyDaughter`](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend#L736-L768)
- [`FamiliesPersonsTest::testSwitchFamilyDifferentPositionLonlySonToFather`](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend#L551-L583)
- [`testExceptionSexChanges_AssignFatherToMother`](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend#L1252-L1268)
- [`testExceptionSexChanges_AssignMotherToFather`](https://github.com/NeumannDirk/Vitruv/blob/master/tests/applications/tools.vitruv.applications.demo.familiespersons.tests/src/tools/vitruv/applications/demo/familiespersons/tests/families2Persons/FamiliesPersonsTest.xtend#L1212-L1228)

2022-03-21 14:45 UTC, NeumannDirk commented on bundles/applications/tools.vitruv.applications.demo.familiespersons/src/tools/vitruv/applications/demo/familiespersons/families2persons/FamiliesToPersons.reactions
> +		with oldValue.eContainer === null
After the last commit the behaviour changed such that the `with affectedEObject.eContainer === null`-check is not needed any longer. It was removed in commit [1d757ff](https://github.com/vitruv-tools/Vitruv/pull/477/commits/1d757ff34f664e27b785738cd6f8f5715e35cf13)

2022-03-21 17:00 UTC, HeikoKlare approved these changes

2022-03-21 17:01 UTC, merged