Support for move operations
vitruv-tools/Vitruv pull request #478
Opened 2021-11-05 09:33 UTC by HansMartinA

2021-11-08 10:03 UTC, HeikoKlare requested changes
Thanks for the improvements! We need to have some regression tests for the covered situations, and we have to investigate whether the additional ID update is necessary in more situations (at least I would expect it to be). This is, however, something we can also provide, so the requested changes do not necessarily need to be performed by you, @HansMartinA, except you require the PR to be merged soon.

2021-11-08 10:03 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change.echange/src/tools/vitruv/framework/change/echange/resolve/EChangeResolverAndApplicator.xtend
> +				}
If I understand correctly, this implementation tries to solve the problem that IDs of root elements can change upon addition/removal of a root element that is not the last within the resource. I would expect this problem to occur for any kind of multi-valued feature (like the root elements of a resource conceptually are), so that we should have such an implementation for any kind of multi-valued feature.
Anyway, we need a regression test for a problematic root change as well as for multi-valued feature changes to see whether the problem occurs there as well.

2022-07-14 12:29 UTC, JanWittler commented
This PR seems to be abandoned. As there are not too many changes in here anyways, I would suggest closing the PR without merging? @HeikoKlare

2022-08-11 14:56 UTC, HeikoKlare commented
Agree

2022-08-11 14:56 UTC, closed without merging