Add insurancePersons reactions and test cases
vitruv-tools/Vitruv pull request #487
Opened 2022-01-25 08:26 UTC by tintengrun

Added reactions for insurance2persons and persons2insurance directions, with corresponding test cases

2022-01-31 16:50 UTC, HeikoKlare requested changes
I have made some rather detailed comments for improvements of the Reactions and some more general comments for the improvement of the test cases. The comments regarding the `InsuranceToPersonsTest` apply in the same way to the `PersonsToInsuranceTest`, I just did not want to repeat them.

Some further general comments that do not apply to single lines of code:
- Code formatting: there are some empty lines, missing whitespaces (in particular before blocks, starting with `{` and false indentations. Please clean up that formatting.
- Code comments: there are some commented out statements (especially `socialSecurityNumber = 000`). Please remove them.
- The test cases have `logger.trace` statements for some kind of lifecycle logging. Are they necessary for anything specific? Otherwise I would be in favor of removing them, because they reduce comprehensibility of the code and will probably not give a benefit, as a test case failure will tell you where it failed anyway.

2022-01-31 16:50 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +			if (client.gender == Gender.MALE) {
Please use a `switch` statement to switch over enum literal values.

2022-01-31 16:50 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +			}
I would propose to have a `switch` over the genders here as well (to ensure that all literals a matched) and then validate whether the person's gender does not correspond to the client's gender within the two `case` statements.

2022-01-31 16:50 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/persons2insurance/PersonsToInsurance.reactions
> +		val insuranceDatabase = retrieve insurance::InsuranceDatabase corresponding to person.eContainer
Same comment as for the other direction:
This implicitly assumes `eContainer` to be a `PersonRegister`, which may fail in case the metamodel changes and persons can be contained somewhere else. I would propose to have a utility method that returns the `PersonRegister` for a personand handles that case that the container is no `PersonRegister` explicitly, e.g., by throwing an exception.

2022-01-31 16:50 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/persons2insurance/PersonsToInsurance.reactions
> +			//newClient.socialSecurityNumber = 000
Remove this line instead of commenting it out.

2022-01-31 16:50 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/persons2insurance/PersonsToInsurance.reactions
> +			}
I would propose to have a `switch` for the type that matches all types of `Person` and also has default behavior for the case that `Person` is neither `Male` nor `Female` as result of potential metamodel change.

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +	TestInfo testInfo = null
It would be sufficient to only store the test naem instead of the complete `TestInfo` object and directly access it instead of extracting the test method name in every test case.

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		assertEquals(0, resourceAt(PERSONS_MODEL).contents.get(0).eAllContents().size);
You may use `head` instead of `get(0)` (applies to all usages of `get(0)`. The only (maybe also useful) difference is that `head` returns `null` in case there is no element while `get(0)` throws an exception.

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +	}
This test case should not exist.

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		//TODO
I guess here should be a validation of the insurance database and person register instead of a "TODO".

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +			insuranceclient += InsuranceFactory.eINSTANCE.createInsuranceClient => [name = FEMALE_NAME_2 gender = Gender.FEMALE]
Format the code so that each assignment is in a single line to improve readability (like it is done below).

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Why have two changes of the gender instead of one here?

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +	def void testChangedName() {
It may also make sense to have test cases for corner cases, for example setting an empty name. The current implementation should handle that the same way as non-empty names are handled, but it might be useful as a regression test.

2022-01-31 16:50 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Please remove this method an create exactly those elements required in a specific test case. Currently this is used as method to generate the highest number of clients required in any of the test, but someone reading the tests must always take a look at this method to comprehend how the model is actually initialized.
In case there is more complex setup logic shared between multiple tests (e.g., creating one male and one female person), you may separate that in a helper method. But then at least the names of the clients should be explicitly passed to that method, so that is is not necessary to read the helper when reading a test case to understand it (and where it possibly fails).

2022-02-01 15:15 UTC, tintengrun commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +			if (client.gender == Gender.MALE) {
What should I put in the `default`-case? My first idea was an IllegalArgumentException

2022-02-01 15:27 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
To check both the male to female as well as female to male change

2022-02-04 10:08 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Okay, then I have two remarks:
1. If both kinds of changes shall be validated, the model state between these two changes should be checked as well.
2. If I understand correctly, with these two changes the resulting model looks exactly like the original model, so if the Reactions do not support gender changes, the test would still succeed. This problem would implicitly be resolved by checking the state between the two changes as proposed in 1. as well.

2022-02-04 10:13 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +			if (client.gender == Gender.MALE) {
If you define a case for each enum literal, there is no essential necessity to have a `default` case. In case another enum literal will be added in the future, the compiler will give a warning. If you want to add a `default` case though, throwing an `IllegalArgumentException` would be fine.

2022-02-07 13:47 UTC, tintengrun commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +			if (client.gender == Gender.MALE) {
Fixed, with an exception in the default case. See commit 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 13:48 UTC, tintengrun commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +			}
Fixed as suggested in 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 13:48 UTC, tintengrun commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/persons2insurance/PersonsToInsurance.reactions
> +			//newClient.socialSecurityNumber = 000
Removed in 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 13:50 UTC, tintengrun commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/persons2insurance/PersonsToInsurance.reactions
> +			}
Fixed in eca4f96fe288d427e735ec480969d57536646d87

2022-02-07 13:51 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +	TestInfo testInfo = null
Removed all manual logging from test cases in insurancepersons. See 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 13:52 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		assertEquals(0, resourceAt(PERSONS_MODEL).contents.get(0).eAllContents().size);
Fixed in 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 13:52 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +	}
Removed test case in 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 13:56 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +			insuranceclient += InsuranceFactory.eINSTANCE.createInsuranceClient => [name = FEMALE_NAME_2 gender = Gender.FEMALE]
Fixed in 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-07 14:01 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Added separate test cases for both m2f and f2m changes, so only one person changes at a time. See bcaa2b3d4dbc241ad68e8896dd93cf1600e3a483

2022-02-07 14:05 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Removed method and instead create all clients where they are needed. See 921b7cb5639471ec829b754d64432b2b8a878f63

2022-02-24 15:01 UTC, tintengrun commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +		val personRegister = retrieve persons::PersonRegister corresponding to client.eContainer
Added helper method in 0104fb8dc6f07e78b411e1bfae5ba2c51bb1d785

2022-02-25 12:28 UTC, HeikoKlare commented on bundles/applications/tools.vitruv.applications.demo.insurancepersons/src/tools/vitruv/applications/demo/insurancepersons/insurance2persons/InsuranceToPersons.reactions
> +		val personRegister = retrieve persons::PersonRegister corresponding to client.eContainer
There were still some `eContainer` references left, which I replaced in d1b8a67.

2022-02-25 12:32 UTC, HeikoKlare commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Now each test case creates the same clients as the auxiliary method created before. However, most test cases do not need to have four clients but less are sufficient, often even one or none. Please reduce the test initialization to what is necessary for the test case to keep it as simple/minimal as possible.

2022-02-25 12:33 UTC, HeikoKlare requested changes
The changes are fine now except for the initialization in the `InsuranceToPersonsTest` cases, which in many cases is overly complex (see detailed comment).

2022-03-02 11:11 UTC, tintengrun commented on tests/applications/tools.vitruv.applications.demo.insurancepersons.tests/src/tools/vitruv/applications/demo/insurancepersons/tests/insurance2persons/InsurancePersonsTest.xtend
> +		]
Slimmed down test cases in acb4a598b3d6173bee36f01bef3e0f8d39b15de1. I left in some test objects that do not change in the test cases where I believe they might be affected if something went wrong

2022-03-02 13:48 UTC, HeikoKlare approved these changes
Great, thanks!

2022-03-03 08:59 UTC, merged