Separate change propagation from VirtualModel
vitruv-tools/Vitruv pull request #501
Opened 2022-03-08 15:53 UTC by HeikoKlare

This PR separate the change propagation concepts of the framework from the `VirtualModel`. As a result, `ChangePropagationSpecifications` do only depend on the specifications of `EChange` and `VitruviusChange` as well as the user interaction definitions, but not on `VitruvDomains` as a `VirtualModel`-specific concept. In addition, the `ChangePropagator` currently integrated into the `VirtualModel` concepts is made independent to be used without a `VirtualModel`.

This involves:
- `ChangePropagationSpecification` accepting namespace URIs of the metamodel rather than `VitruvDomains`
- Introduction of `ChangeInPropagation` that decoples the information about whether a change shall be propagated transitively from accessing the `VitruvDomains` that are currently the only source for deciding on transitive propagation.
- `ChangePropagator`:
  - Operating on namespaces, depending on a lean `ChangeRecordingModelRepository`, which is implemented by the `ModelRepository` of the `VirtualModel`, rather than on `VitruvDomains`
  - Transferring the knowledge about transitive change propagation from access to `VitruvDomains` to an explicit specification in a `ChangeInProgress` delivered by the `ChangeRecordingModelRepository`, which makes the decision for transitive propagation

With this PR, the `tools.vitruv.framework.propagation` bundle together with the change representation specifications can be used independent from the virtual model, domains and applications to implement change propagation. A subsequent PR will adapt the DSLs (Reactions, Mappings, Commonalities) to also depend on metamodel rather than domains.
In a future PR, we may also add a default implementation for the `ChangeRecordingModelRepository` to have ready-to-use implementations for all change propagation artifacts to be used without a `VirtualModel`.

2022-03-11 10:01 UTC, JanWittler reviewed
I made pretty picky comments as these code parts will probably not be touched for a while.

In general I like the proposed changes, I am just questioning myself whether the approach to work directly on the nsURIs is the best. It makes the accessor names pretty long and we lose some type safety. The alternative would be to introduce some lightweight interface like `ChangeDomain` or similar that encapsulates the nsURIs. However, having an interface to only encapsulate one property can be considered as unnecessary overhead.
What were your decisive arguments to throw away the domain concept in the change context?

2022-03-11 14:04 UTC, HeikoKlare commented
Thanks for the review. The reason why we want to get rid of the domain is that they are a concept that is only used in the `VirtualModel` in particular for reasons of persistence (save/load options etc.). To use the consistency preservation DSLs, the metamodels to be defined on have to specified in present `VitruvDomains`, which have to be provided in the registry provided via Eclipse extension mechanis. However, the only property consistency preservation needs to use are the metamodels. And in EMF, metamodels are accessed by their nsURI, which is why I used them to refer to the metamodels. An alternative would be `EPackages`, but they are only an implementation artifact of the metamodels and may even not be represented as a dedicated class we can statically refer to but as an instance of `EPackage`. Wrapping an nsURI within some "domain" class will not solve the problem of missing type safety, as you can enter whatever nsURI you want into that domain as well. And finally it is again an object to wrap around the EMF metamodel reference, the nsURI, like the `VitruvDomains` before, only in a more lightweight fashion.
These are the general reasons for using nsURIs to refer to metamodels

2022-03-11 14:05 UTC, HeikoKlare commented on bundles/dsls/tools.vitruv.dsls.commonalities/src/tools/vitruv/dsls/commonalities/generator/reactions/ReactionsGenerator.xtend
> +		.withInitializedMetamodel(commonality.concept.intermediateMetamodelPackageClassName.qualifiedName)
For reasons of readability. Otherwise, auto-formatting will make linebreakes within the arguments of the method calls, thus we may either not use auto-formatting or degrade readability instead.

2022-03-11 14:05 UTC, HeikoKlare commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/ViewBasedVitruvApplicationTest.xtend
> +		.withDomainRepository(domains) //
Like above: For reasons of readability. Otherwise, auto-formatting will make linebreakes within the arguments of the method calls, thus we may either not use auto-formatting or degrade readability instead.

2022-03-11 14:05 UTC, HeikoKlare commented on bundles/testutils/tools.vitruv.testutils/src/tools/vitruv/testutils/VitruvApplicationTest.xtend
> +		.withDomainRepository(domains) //
Like above: For reasons of readability. Otherwise, auto-formatting will make linebreakes within the arguments of the method calls, thus we may either not use auto-formatting or degrade readability instead.

2022-03-11 14:11 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/impl/TransactionalChangeImpl.xtend
> +	}
Yes, fixed in 39a8227.

2022-03-11 14:17 UTC, JanWittler commented on bundles/dsls/tools.vitruv.dsls.commonalities/src/tools/vitruv/dsls/commonalities/generator/reactions/ReactionsGenerator.xtend
> +		.withInitializedMetamodel(commonality.concept.intermediateMetamodelPackageClassName.qualifiedName)
Ah ok. Maybe we can come up with a cleaner solution in scope of #495

2022-03-11 14:21 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
There are different style guidelines on capitalizations of acronyms. We have decided some time ago to adapt the guideline of only writing acronyms in uppercase letters when they consist of two letters and to write all longer acronyms using pascal case, because composed words containing acronyms often look weird otherwise. This is why we had `Uuid` and also use `Uri`. We may, of couse, adapt the capitalization used by EMF in that case as we refer to the EMF URI concept. I don't have a strong opinion on that, only that I am a little worried that we then may reach some point where we need to discuss when we actually refer to an existing concept and when it is our own one. This issue does not come up if we simply say that we always follow that style guideline not matter whether we refer to an existing concept with a different capitalization or not.

2022-03-11 14:21 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.domains/src/tools/vitruv/framework/domains/repository/VitruvDomainRepository.java
> +	VitruvDomain getDomainForNsUri(String nsUri);
See my comment above.

2022-03-11 14:25 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
I don't have a strong opinion about that neither, just wanted it to be consistent. So I'm fine with the current naming.
Maybe this convention is worth a paragraph in Wiki -> Contribution -> Development?

2022-03-11 15:41 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecification.xtend
> +}
Yes, I've added documentation for this interface.

2022-03-11 15:41 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangeInPropagation.xtend
> +}
Added in e0a6192.

2022-03-11 15:42 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
Indeed. I will add some documentation.

2022-03-11 15:50 UTC, HeikoKlare commented on bundles/dsls/tools.vitruv.dsls.reactions/model/TopLevelElements.ecore
> +        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
This is, indeed, a kind of workaround for the Commonalities. It may be used beyond that if someone requires to have some further metamodels initialized when running a Reactions specification, but I don't any necessity to so yet.
The metamodels that the Commonalities need to register are, however, project-specific, such that we cannot have a predefined set provided by an enum. More precisely, this attribute is required to register the metamodels representing the concepts, i.e., the metamodels of the commonalities of two existing metamodels, which are different from project to project.

I totally agree that neither the functionality nor the name is pretty good, so I would be glad to find a better solution/naming. Something like `qualifiedClassNamesOfAdditionalMetamodelPackagesToInitialize` may be slightly better to understand but does still not look like a final solution to me.

2022-03-11 15:57 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
Added: https://github.com/vitruv-tools/Vitruv/wiki/Development#acronyms

2022-03-11 17:12 UTC, JanWittler requested changes

2022-03-11 17:12 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecification.xtend
> +	 * Returns the namespace UIs of the root packages of the metamodel of elements whose changes
"namespace URI"

2022-03-11 17:12 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecification.xtend
> +	 * Returns the namespace UIs of the root packages of the metamodel of elements whose are changed
"namespace URI"

2022-03-11 17:34 UTC, JanWittler commented on bundles/dsls/tools.vitruv.dsls.reactions/model/TopLevelElements.ecore
> +        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
For me this sounds like a dependency problem. As far as I understand, the Commonalities are a "wrapper language" for the Reactions and internally compile to them. So in a perfect world, the Reactions implementation should not be aware that the Commonalities exist at all and thus not need to include a workaround for them. Subclassing or offering extension points in the `ChangePropagationSpecificationClassGenerator` is no option?
We can keep the change as it is for now as this is not really related to this PR, however I would at least leave a comment in the generator that currently this attribute is only necessary for the workaround and if possible should be fixed. If you think it is theoretically possible to resolve this workaround, we could also create an issue for it.

2022-03-11 17:48 UTC, JanWittler commented
> Wrapping an nsURI within some "domain" class will not solve the problem of missing type safety, as you can enter whatever nsURI you want into that domain as well. And finally it is again an object to wrap around the EMF metamodel reference, the nsURI, like the VitruvDomains before, only in a more lightweight fashion.

I totally agree with your arguments. The benefit I see with an interface - besides shorter attribute names - was the possibility to have a centralized documentation (like how to retrieve nsURIs or what they represent). If using a data class, we could even implement some validation to the URIs. However, these are not the strongest arguments to motivate a refactoring. Additionally, as I'm coming from the Swift language domain where interfaces are far more lightweight, maybe I am a bit biased on the overhead of such an additional interface.
Therefore, I am fine with sticking to the current solution.

2022-03-15 16:18 UTC, HeikoKlare commented on bundles/dsls/tools.vitruv.dsls.reactions/model/TopLevelElements.ecore
> +        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
You are totally right. The difficulty is that the Commonalities language creates Reactions using the Reactions builder and then only calls the Reactions language generator. Thus hooking into the Reactions-to-code generation is not that simple.

To address this issue, I have implemented the generation of combined `ChangePropagationSpecifications` for Commonalities in #504. After merging that PR, we can add the registration of Commonalities-specific metamodels in these combined `ChangePropagationSpecifications` such that they do not need to be passed to the Reactions anymore.

2022-03-21 17:31 UTC, HeikoKlare commented on bundles/dsls/tools.vitruv.dsls.reactions/model/TopLevelElements.ecore
> +        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
I have finally removed this workaround in c90494a since the Commonalities register the additional concept metamodels on their own (#504).

2022-03-22 08:32 UTC, JanWittler commented on bundles/dsls/tools.vitruv.dsls.reactions/model/TopLevelElements.genmodel
> +      <genFeatures createChild="false" ecoreFeature="ecore:EAttribute TopLevelElements.ecore#//ReactionsSegment/additionalInitializedMetamodelPackageQualifiedClassNames"/>
This should be removed after the refactoring too I guess?

2022-03-23 08:30 UTC, HeikoKlare commented on bundles/dsls/tools.vitruv.dsls.reactions/model/TopLevelElements.genmodel
> +      <genFeatures createChild="false" ecoreFeature="ecore:EAttribute TopLevelElements.ecore#//ReactionsSegment/additionalInitializedMetamodelPackageQualifiedClassNames"/>
Of course. I've removed that.

2022-03-23 08:35 UTC, HeikoKlare commented
Regarding the namespace URIs: I agree that encapsulating the URIs makes sense. I've proposed a `Metamodel` class in 261b0ef that encapsulates the namespace URIs of a metamodel. Is this like you have expected? Maybe we can have a better name than the generic `Metamodel`, but I think that encapsulating a namespace URI is not specific to a "change" and the word "domain" is quite overloaded in Vitruv, which is why I did not use the term `ChangeDomain`, but we can of course discuss that.

2022-03-23 13:34 UTC, JanWittler reviewed
Yes, the encapsulating is as I would have expected it.
Regarding the naming: I also think that metamodel is suboptimal, as the class itself does not _model_ anything or contain model elements.
I was thinking about what we really want to express with the class. The nsURIs are the location of the metamodel of the domain. The class itself has no actual functionality but serves as a wrapper. Regarding overloading of the "domain" word, are there other concepts than the `VitruvDomain`?

I was thinking of `DomainDescriptor` / `DomainDescription` or similar? And if we want to be precise we could name the uri attribute then `metamodelNsUris`.

2022-03-23 13:34 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/Metamodel.xtend
> +	}
Not sure about run time but I would guess initializing and adding elements takes more time than creating a new hash set out of the passed `nsURIs`, i.e. calling in the initializer `this.nsURIs = new HashSet(nsURIs)` and not having a default initializer.

2022-03-23 13:34 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/Metamodel.xtend
> +class Metamodel {
I'm thinking about whether we should make this class `final`? As it is currently only a data wrapper, we do not really need to extend it right?

2022-03-24 14:46 UTC, HeikoKlare commented
There are no other concepts except for the `VitruvDomain`, but the main purpose for calling it a domain was that it contains (a) metamodel(s) and, in particular, additional information around it. In this case, however, the class does only describe a metamodel and does nor provide addition domain information.
Calling it a "descriptor" or "description" makes sense. Why not call it something like `MetamodelDescriptor`?

2022-03-24 14:48 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
Yes, done in 30da620. I also had to move the `Metamodel` (or whatever it will be called after this PR) from the propagation to the change plugin to make it available for the change description. We could also think about having the `Metamodel` class in the `util` plugin of the framework as it does actually not relate to any of the specific plugins.

2022-03-24 14:48 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/Metamodel.xtend
> +	}
That's true, it makes initialization faster. Fixed in 85f03da.

2022-03-24 14:49 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/Metamodel.xtend
> +class Metamodel {
Yes, fixed in 4b44b39.

2022-03-24 15:24 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
You mean in `tools.vitruv.framework.util`?
I would rather prefer to keep it in the change plugin as the class is only required in the scope of change and change propagation.

2022-03-24 15:51 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
While talking about this: Do we really need this method? It loops over the `affectedEObjects` and collects their packages. We could also do this in a utility function and loop over `VitruviusChange#getAffectedEObjects()`. Runtime-wise I don't see an overhead, as for the current approach we need to collect the affected objects too.
With that change I guess it would be possible again to move the `MetamodelDescriptor` to the propagation package.

2022-03-25 14:10 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
The method does, in its current implementation, actually not only retrieve the packages / namespace URIs / metamodels for the `affectedEObjects`, but has a different semantics for a `TransactionalChange` and a `CompositeChange`. While for the former a single metamodel of all namespace URIs / packages of the `affectedEObjects` is returned, the latter simply returns a set of all metamodels of the contained `TransactionalChanges`. The idea is that a `TransactionalChange` affects only one metamodel while a `CompositeChange` may affect multiple metamodels.
We can still move that a utility method but then have to make a case distinction based in the inheritance hierarchy of the `VitruviusChange`.

2022-03-25 15:04 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
I see, then it makes sense to have the method. Maybe it would be helpful to annotate the implemented methods with these details or add the assumptions about single / multiple metamodels to the interface documentation (for transactional and composite change). 
For a transactional change we could even make this explicit by adding a `def String getAffectedEObjectsMetamodelDescriptor()` method there and a default implementation of the set returning method that returns a set consisting only of the one element from the newly added method.

2022-03-25 15:48 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
That makes sense. I've added a proposal in d186f81.
I don't think the implementation breaks clean code conventions, even though, of course, one might override the default implementation. But then it must still conform to its documentation in `VitruviusChange`. The only drawback is that the documentation of `VitruviusChange` now refers to the `TransactionalChange` subclass.

2022-03-25 17:13 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/TransactionalChange.xtend
> +	 * Returns the unique metamodel descriptor for the for the metamodels of the elements whose instances
"for the" duplicated

2022-03-28 06:32 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/TransactionalChange.xtend
> +	 * Returns the unique metamodel descriptor for the for the metamodels of the elements whose instances
Fixed in 5478d5b.

2022-03-28 06:33 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/VitruviusChange.xtend
> +	def Set<String> getAffectedEObjectsMetamodelRootNsUris()
True, the change-specific documentation is now givne in `TransactionalChange` and `CompositeChange` but not in `VitruviusChange` anymore (5478d5b).

2022-03-28 06:52 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/CompositeChange.xtend
> +	 * Returns the metamodel descriptors for the for the metamodels of the elements whose instances
Once more "for the" duplicate

2022-03-28 07:13 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/CompositeChange.xtend
> +	 * Returns the metamodel descriptors for the for the metamodels of the elements whose instances
I'm sorry... Fixed in e767053.

2022-03-28 09:33 UTC, JanWittler reviewed
Looks good!
I only added some minor comments regarding documentation.

2022-03-28 09:33 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/MetamodelDescriptor.xtend
> +	 */
is is
descriptorForPpotentially -> Pp

2022-03-28 09:33 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecification.xtend
> +	 * 								source metamodel of this specification (see {@link #getSourceMetamodelDescriptor}).
"Should be in an instance of a source metamodel" sounds strange. Maybe "Should affect elements in an instance of a source metamodel"? 
I guess an atomic change can only affect elements of one metamodel at a time right? Otherwise we could also say "Should affect only elements ..." if we require that

2022-03-28 09:33 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecificationProvider.xtend
> +	 * Delivers change propagation specifications that react to changes in instances of the
"Delivers" -> "Returns"?
Delivers sounds like the specifications are delivered to somewhere else

2022-03-28 11:07 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/MetamodelDescriptor.xtend
> +	 */
Fixed in 853f024.

2022-03-28 11:08 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecification.xtend
> +	 * 								source metamodel of this specification (see {@link #getSourceMetamodelDescriptor}).
It does not only sound strange but is actually even wrong 😉 
Fixed in 35e4b24.

2022-03-28 11:09 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.propagation/src/tools/vitruv/framework/propagation/ChangePropagationSpecificationProvider.xtend
> +	 * Delivers change propagation specifications that react to changes in instances of the
True, fixed in 35e4b24.

2022-03-28 11:22 UTC, JanWittler commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/MetamodelDescriptor.xtend
> +	 */
I added the fix for "is is" in https://github.com/vitruv-tools/Vitruv/pull/501/commits/18fdc7333790f4277f3800e7645990e349007943

2022-03-28 11:23 UTC, JanWittler approved these changes

2022-03-28 11:42 UTC, HeikoKlare commented on bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/MetamodelDescriptor.xtend
> +	 */
Ah, thanks! I didn't see that there were two corrections :-(

2022-03-28 13:56 UTC, merged